[preface]

== 서론

=== 비트코인 책 쓰기

((("bitcoin", "benefits of", id="BCbasicbenefits0")))((("decentralized systems", "bitcoin as"))) 나는 2011년 중반에 처음 비트코인을 접했다. 나의 즉각적인 반응은
"풋.. 머저리 돈" 이었다. 나는 그 중요성을 이해하지 못했고 6개월동안 무시했었다. 이것은 내가 아는 똑똑한 사람들 사이에서도 반복적으로 보였고 나는 위안이 되었다. 메일링 리스트에서 두번째로 비트코인을 만났을 때, 나카모토 사토시가 작성한 백서를 읽고 권위있는 출처를 공부하고 그것이 무엇인지 알아보기로 결정했다. 그 백서 9페이지를 읽고나서 비트코인이 단순한 디지털 통화가 아니라 단순 통화 이상의 신뢰의 네트워크라는 것을 깨달았던 순간을 아직도 기억하고 있다. "비트코인은 돈이 아니며 분산 된 신뢰 네트워크이다"라는 깨달음에 내가 발견 할 수 있는 비트코인에 관련된 모든 정보 스크랩 탐독하기 위해 4개월간의 여정을 시작했다. 매일 적어도 12시간 이상을 화면에 붙이고 읽고, 쓰고, 코딩하고 학습하는데 사로 잡혔다. fugue상태(?) 에서 비트코인 작업에 전념하기로 결심한 후 일관된 식사 부족으로 20 파운트 이상 가벼워 졌었다.

2년 후, 비트코인과 관련된 다양한 서비스 및 제품을 탐색 할 수 있는 소규모 스타트업이 만들어지고 난 후 첫 번째 서적을 작성 할때가 되었다고 판단했다. 비트코인은 나를 창의력의 광란으로 몰고 내 생각을 소모시킨 주제 였고 그것은 내가 인터넷에서 만난 가장 흥미로운 기술이었다. 이제 이 놀라운 기술에 대한 나의 열정을 더 많은 사람들과 나눠야 할 때 이다. 

=== 대상 독자

((("intended audience"))) 이 책은 주로 코더를 위한 책이다. 당신이 프로그래밍 언어를 다룰 수 있는 경우 이 책은 암호화 통화의 작동방식, 사용방법 및 함께 작동하는 소프트웨어 개발 방법을 알려준다. 처음 몇 장은 비 코더 (bitcoin과 cryptocurrencies의 내부 동작을 이해하려는 사람들)를위한 비트 코어에 대한 심층적인 소개로도 적합하다.

=== 표지에 곤충이 있는 이유가 뭔가요?

((("decentralized systems", "in nature"))) 가위개미(leafcutter ant)는 초 유기체 집단에서 고도로 복잡한 행동을 타나내는 종 이지만 개개의 개미는 사회적 상호 작용과 화학 향(페로몬) 교환에 의한 일련의 단순한 규칙에 따라 작동한다. 위키피이다 인용 : "가위개미는 지구상에서 인간 다음으로 가장 크고 복잡한 동물 사회를 형성한다." 가위개미는 사실 잎을 먹지 않고 오히려 그것을 이용하여 식민지의 중심적인 식량 공급원인 공팜이를 기른다. 그것 아나? 이 개미는 농사를 짖는다고!

비록 개미들은 계급 기반 사회를 형성하고 자손을 낳기 위한 여왕을 가지고 있지만 개미 식민지에는 중앙권위나 지도자가 없다. 수백만 마리의 집단에 의해 나타나는 고도로 지능적이고 정교한 행동은 소설 네트워크에서 개인의 상호작용에서 창발 된 속성이다.

자연은 분산된 시스템이 탄력적 일 수 있으며 중앙권한, 계층구조 또는 복잡한 부분을 필요로 하지 않으면서 창발적인 복잡성과 믿을 수 없는 정교함을 생성 할 수 있음을 보여준다.

((("decentralized systems", "benefits of")))Bitcoin은 수많은 재무 프로세스를 지원할 수있는 고도로 정교한 분산의 신뢰 네트워크이며 게다가 비트 코인 네트워크의 각 노드는 몇 가지 간단한 수학적 규칙을 따른다. 많은 노드 사이의 상호 작용은 정교한 동작의 출현으로 이어져 하나의 노드에 고유의 복잡성과 신뢰성을 제공하지는 않는다. 개미 식민지처럼, 비트 코인 네트워크는 중앙의 조정없이 놀라운 일을 함께 할 수있는 간단한 규칙을 따르는 간단한 노드의 탄력적 인 네트워크이다.((("", startref="BCbasicbenefits0")))

=== 이 책에 사용된 규칙

((("typographical conventions")))이 책에는 다음과 같은 인쇄 규칙을 사용한다:

_이탤릭체_:: 새로운 용어, URL, email, 파일명 및 파일 확장자를 나타낸다.

+고정폭+:: 프로그램 목록, 변수, 함수 이름, 데이터베이스, 데이터 형, 환경 변수, 명령문, 키워드 등의 프로그램 요소를 참조하는 단락에 사용된다.

**`고정폭 굵은체`**:: 문자 그래도 사용자가 입력해야 하는 명령 또는 기타 텍스트를 표시한다.

_++고정폭 이탤릭++_:: 사용자 제공 값 또는 문맥에 의해 결정된 값으로 대체 해야할 텍스트를 표시한다.


[TIP]
====
이 아이콘은 팁 또는 제안을 의미한다.
====

[NOTE]
====
이 아이콘은 일반적인 참고사항을 의미한다.
====

[WARNING]
====
이 아이콘은 경고 또는 주의를 나타낸다.
====

=== 코드 예제

((("code examples, obtaining and using", id="codeuse00")))The examples are illustrated in Python, C++, and using the command line of a Unix-like operating system such as Linux or macOS. All code snippets are available in the https://github.com/aantonop/bitcoinbook[GitHub repository] in the _code_ subdirectory of the main repo. Fork the book code, try the code examples, or submit corrections via GitHub.

All the code snippets can be replicated on most operating systems with a minimal installation of compilers and interpreters for the corresponding languages. Where necessary, we provide basic installation instructions and step-by-step examples of the output of those instructions.

Some of the code snippets and code output have been reformatted for print. In all such cases, the lines have been split by a backslash (\) character, followed by a newline character. When transcribing the examples, remove those two characters and join the lines again and you should see identical results as shown in the example.

All the code snippets use real values and calculations where possible, so that you can build from example to example and see the same results in any code you write to calculate the same values. For example, the private keys and corresponding public keys and addresses are all real. The sample transactions, blocks, and blockchain references have all been introduced in the actual bitcoin blockchain and are part of the public ledger, so you can review them on any bitcoin system.

=== Using Code Examples

This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you’re reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing a CD-ROM of examples from O’Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product’s documentation does require permission.

((("attribution")))We appreciate, but do not require, attribution. An attribution usually includes the title, author, publisher, and ISBN. For example: “_Mastering Bitcoin_ by Andreas M. Antonopoulos (O’Reilly). Copyright 2017 Andreas M. Antonopoulos, 978-1-491-95438-6.”

((("open source licenses")))Some editions of this book are offered under an open source license, such as https://creativecommons.org/licenses/by-nc/4.0/[CC-BY-NC], in which case the terms of that license apply.

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>].

=== Bitcoin Addresses and Transactions in This Book

((("getting started", "warnings and cautions")))((("warnings and cautions", "avoid sending money to addresses appearing in book")))((("keys and addresses", "warnings and cautions")))((("transactions", "warnings and cautions")))((("blockchain applications", "warnings and cautions")))((("QR codes", "warnings and cautions")))The bitcoin addresses, transactions, keys, QR codes, and blockchain data used in this book are, for the most part, real. That means you can browse the blockchain, look at the transactions offered as examples, retrieve them with your own scripts or programs, etc.

However, note that the private keys used to construct addresses are either printed in this book, or have been "burned." That means that if you send money to any of these addresses, the money will either be lost forever, or in some cases everyone who can read the book can take it using the private keys printed in here.

[WARNING]
====
DO NOT SEND MONEY TO ANY OF THE ADDRESSES IN THIS BOOK. Your money will be taken by another reader, or lost forever.((("", startref="codeuse00")))
====

=== O'Reilly Safari

[role = "safarienabled"]
[NOTE]
====
pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em class="hyperlink">Safari</em></a>] (formerly Safari Books Online) is a membership-based training and reference platform for enterprise, government, educators, and individuals.
====

Members have access to thousands of books, training videos, Learning Paths, interactive tutorials, and curated playlists from over 250 publishers, including O’Reilly Media, Harvard Business Review, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Adobe, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, and Course Technology, among others.

For more information, please visit pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em>http://oreilly.com/safari</em></a>].

=== How to Contact Us

((("comments and questions")))((("contact information")))Please address comments and questions concerning this book to the publisher:

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (in the United States or Canada)</li>
  <li>707-829-0515 (international or local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

To comment or ask technical questions about this book, send email to pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

For more information about our books, courses, conferences, and news, see our website at link:$$http://www.oreilly.com$$[].

Find us on Facebook: link:$$http://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$http://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$http://www.youtube.com/oreillymedia$$[]

[role="pagebreak-before"]
=== Contacting the Author

You can contact me, Andreas M. Antonopoulos, on my personal site:
link:$$https://antonopoulos.com/$$[]

Information about _Mastering Bitcoin_ as well as the Open Edition and translations are available on:
link:$$https://bitcoinbook.info/$$[]

Follow me on Facebook:
link:$$https://facebook.com/AndreasMAntonopoulos$$[]

Follow me on Twitter:
link:$$https://twitter.com/aantonop$$[]

Follow me on Linkedin:
link:$$https://linkedin.com/company/aantonop$$[]

Many thanks to all my patrons who support my work through monthly donations. You can follow my Patreon page here:
link:$$https://patreon.com/aantonop$$[]

=== Acknowledgments

((("acknowledgments", id="acknowledge0")))This book represents the efforts and contributions of many people. I am grateful for all the help I received from friends, colleagues, and even complete strangers, who joined me in this effort to write the definitive technical book on cryptocurrencies and bitcoin.

It is impossible to make a distinction between the bitcoin technology and the bitcoin community, and this book is as much a product of that community as it is a book on the technology. My work on this book was encouraged, cheered on, supported, and rewarded by the entire bitcoin community from the very beginning until the very end. More than anything, this book has allowed me to be part of a wonderful community for two years and I can't thank you enough for accepting me into this community. There are far too many people to mention by name—people I've met at conferences, events, seminars, meetups, pizza gatherings, and small private gatherings, as well as many who communicated with me by Twitter, on reddit, on bitcointalk.org, and on GitHub who have had an impact on this book. Every idea, analogy, question, answer, and explanation you find in this book was at some point inspired, tested, or improved through my interactions with the community. Thank you all for your support; without you this book would not have happened. I am forever grateful.

The journey to becoming an author starts long before the first book, of course. My first language (and schooling) was Greek, so I had to take a remedial English writing course in my first year of university. I owe thanks to Diana Kordas, my English writing teacher, who helped me build confidence and skills that year. Later, as a professional, I developed my technical writing skills on the topic of data centers, writing for _Network World_ magazine. I owe thanks to John Dix and John Gallant, who gave me my first writing job as a columnist at _Network World_ and to my editor Michael Cooney and my colleague Johna Till Johnson who edited my columns and made them fit for publication. Writing 500 words a week for four years gave me enough experience to eventually consider becoming an author.

Thanks also to those who supported me when I submitted my book proposal to O'Reilly, by providing references and reviewing the proposal. Specifically, thanks to John Gallant, Gregory Ness, Richard Stiennon, Joel Snyder, Adam B. Levine, Sandra Gittlen, John Dix, Johna Till Johnson, Roger Ver, and Jon Matonis. Special thanks to Richard Kagan and Tymon Mattoszko, who reviewed early versions of the proposal and Matthew Taylor, who copyedited the proposal.

Thanks to Cricket Liu, author of the O'Reilly title _DNS and BIND_, who introduced me to O'Reilly. Thanks also to Michael Loukides and Allyson MacDonald at O'Reilly, who worked for months to help make this book happen. Allyson was especially patient when deadlines were missed and deliverables delayed as life intervened in our planned schedule. For the second edition, I thank Timothy McGovern for guiding the process, Kim Cofer for patiently editing, and Rebecca Panzer for illustrating many new diagrams.

The first few drafts of the first few chapters were the hardest, because bitcoin is a difficult subject to unravel. Every time I pulled on one thread of the bitcoin technology, I had to pull on the whole thing. I repeatedly got stuck and a bit despondent as I struggled to make the topic easy to understand and create a narrative around such a dense technical subject. Eventually, I decided to tell the story of bitcoin through the stories of the people using bitcoin and the whole book became a lot easier to write. I owe thanks to my friend and mentor, Richard Kagan, who helped me unravel the story and get past the moments of writer's block. I thank Pamela Morgan, who reviewed early drafts of each chapter in the first and second edition of the book, and asked the hard questions to make them better. Also, thanks to the developers of the San Francisco Bitcoin Developers Meetup group as well as Taariq Lewis and Denise Terry for helping test the early material. Thanks also to Andrew Naugler for infographic design.

During the development of the book, I made early drafts available on GitHub and invited public comments. More than a hundred comments, suggestions, corrections, and contributions were submitted in response. Those contributions are explicitly acknowledged, with my thanks, in <<github_contrib>>. Most of all, my sincere thanks to my volunteer GitHub editors Ming T. Nguyen (1st edition) and Will Binns (2nd edition), who worked tirelessly to curate, manage and resolve pull requests, issue reports, and perform bug fixes on GitHub.

Once the book was drafted, it went through several rounds of technical review. Thanks to Cricket Liu and Lorne Lantz for their thorough review, comments, and support.

Several bitcoin developers contributed code samples, reviews, comments, and encouragement. Thanks to Amir Taaki and Eric Voskuil for example code snippets and many great comments; Chris Kleeschulte for contributing the Bitcore appendix; Vitalik Buterin and Richard Kiss for help with elliptic curve math and code contributions; Gavin Andresen for corrections, comments, and encouragement; Michalis Kargakis for comments, contributions, and btcd writeup; and Robin Inge for errata submissions improving the second print. In the second edition, I again received a lot of help from many Bitcoin Core developers, including Eric Lombrozo who demystified Segregated Witness, Luke-Jr who helped improve the chapter on transactions, Johnson Lau who reviewed Segregated Witness and other chapters, and many others. I owe thanks to Joseph Poon, Tadge Dryja, and Olaoluwa Osuntokun who explained Lightning Network, reviewed my writing, and answered questions when I got stuck.

I owe my love of words and books to my mother, Theresa, who raised me in a house with books lining every wall. My mother also bought me my first computer in 1982, despite being a self-described technophobe. My father, Menelaos, a civil engineer who just published his first book at 80 years old, was the one who taught me logical and analytical thinking and a love of science and engineering.

Thank you all for supporting me throughout this journey.

[[github_contrib]]
==== Early Release Draft (GitHub Contributions)

Many contributors offered comments, corrections, and additions to the early-release draft on GitHub. Thank you all for your contributions to this book.

Following is a list of notable GitHub contributors, including their GitHub ID in parentheses:

* Alex Waters (alexwaters)
* Andrew Donald Kennedy (grkvlt)
* bitcoinctf
* Bryan Gmyrek (physicsdude)
* Casey Flynn (cflynn07)
* Chapman Shoop (belovachap)
* Christie D'Anna (avocadobreath)
* Cody Scott (Siecje)
* coinradar
* Cragin Godley (cgodley)
* dallyshalla
* Diego Viola (diegoviola)
* Dirk Jäckel (biafra23)
* Dimitris Tsapakidis (dimitris-t)
* Dmitry Marakasov (AMDmi3)
* drstrangeM
* Ed Eykholt (edeykholt)
* Ed Leafe (EdLeafe)
* Edward Posnak (edposnak)
* Elias Rodrigues (elias19r)
* Eric Voskuil (evoskuil)
* Eric Winchell (winchell)
* Erik Wahlström (erikwam)
* effectsToCause (vericoin)
* Esteban Ordano (eordano)
* ethers
* fabienhinault
* Frank Höger (francyi)
* Gaurav Rana (bitcoinsSG)
* genjix
* halseth
* Holger Schinzel (schinzelh)
* Ioannis Cherouvim (cherouvim)
* Ish Ot Jr. (ishotjr)
* James Addison (jayaddison)
* Jameson Lopp (jlopp)
* Jason Bisterfeldt (jbisterfeldt)
* Javier Rojas (fjrojasgarcia)
* Jeremy Bokobza (bokobza)
* JerJohn15
* Joe Bauers (joebauers)
* joflynn
* Johnson Lau (jl2012)
* Jonathan Cross (jonathancross)
* Jorgeminator
* Kai Bakker (kaibakker)
* Mai-Hsuan Chia (mhchia)
* Marzig (marzig76)
* Maximilian Reichel (phramz)
* Michalis Kargakis (kargakis)
* Michael C. Ippolito (michaelcippolito)
* Mihail Russu (MihailRussu)
* Minh T. Nguyen (enderminh)
* Nagaraj Hubli (nagarajhubli)
* Nekomata (nekomata-3)
* Robert Furse (Rfurse)
* Richard Kiss (richardkiss)
* Ruben Alexander (hizzvizz)
* Sam Ritchie (sritchie)
* Sergej Kotliar (ziggamon)
* Seiichi Uchida (topecongiro)
* Simon de la Rouviere (simondlr)
* Stephan Oeste (Emzy)
* takaya-imai
* Thiago Arrais (thiagoarrais)
* venzen
* Will Binns (wbnns)
* wintercooled
* wjx
* Wojciech Langiewicz (wlk)
* yurigeorgiev4((("", startref="acknowledge0")))
